import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import localFont from "next/font/local";

const ceraPro = localFont({
  src: [
    {
      path: "../public/cera-pro/Fontspring-DEMO-cerapro-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/cera-pro/Fontspring-DEMO-cerapro-medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-cera-pro"
});

const ceraStencil = localFont({
  src: [
    {
      path: "../public/cera-stencil/Cera-Stencil-Regular-Demo.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/cera-stencil/Cera-Stencil-Bold-Demo.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-cera-stencil"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ceraPro.variable} ${ceraStencil.variable}`}>
      <body className={`${ceraPro.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}